### ISSUE TITLE
Documentation wrong on the 2.0.x branch

### ISSUE THREAD

**Issue by FrostbittenKing** [naparuba/shinken#1441] opened 2015-01-07 20:56 UTC
Are you still maintaining the documentation, because I believe it needs some serious updating.
* According to http://shinken.readthedocs.org/en/latest/13_monitoring/windows-monitoring-with-nsclient.html there should be a commands.cfg file. Nope there isn't . It seems like it has been split up into several files in the commands directory. 
* According to the same wiki page, there should be a templates.cfg file, nope not anymore.
* > The check_nt plugin should already be installed on the Shinken server if you followed the quickstart guide.
   Maybe, but in debian it is installed in /etc/nagios-plugins (if I'm correct).
Not quite sure how to proceed, since there is nothing matching the documentation (at least regarding the windows nsclient++ doc page.

Sorry, for sounding annoyed, but this documentation is unusable in this state.

**Comment by david-guenault** [comment] 2015-01-08 05:39
Hello thank's for reporting. As you may know the documentation is maintained by the community and i don't think there are a lot of people using nsclient or check_nt. This could explain why this part of documentation is outdated. The documentation sources are in the documentation folder on this github repository. Help will be welcome if you could make a PR to fix this. If not we will fix it as soon as possible.

**Comment by naparuba** [comment] 2015-01-08 09:51
Such page should be deleted from the documentation. The good place is in
the pack documentation, not on the framework one.

I'll remove it.

**Comment by FrostbittenKing** [comment] 2015-01-08 10:04
Seems, like I got unlucky by picking the part that is documented the worst :D. The problem is, this documentation is really old. I first installed shinken with apt-get, and according to the output, v 0.6.5.2 (or something really old was installed). The documentation matched more or less this version ^^.
> Hello thank's for reporting. As you may know the documentation is maintained by the community and i don't think there are a lot of people using nsclient or check_nt. 
Since you mentioned that not many people use nsclient/check_nt, what would you suggest? Using the polling method? I'm not a fan of polling, and as I see it, this part of the documentation is outdated too.
> The documentation sources are in the documentation folder on this github repository. Help will be welcome if you could make a PR to fix this. If not we will fix it as soon as possible. 
I would do that after I got the overall picture, how shinken works, which I still don't since the documentation needs to be updated (chicken and egg problem).
There are so many different ways to run it. One website suggests to install everything via the created shinken user, the other via root (since the user is created without a login shell / /bin/false).
I still couldn't wrap my head around it.
> The good place is in the pack documentation, not on the framework one.
What exactly do you mean by pack documentation? I'm not too much inclined to read the man pages ;).

**Comment by FrostbittenKing** [comment] 2015-01-08 17:21
Gnaa. The documentation is not completely wrong. It depends on how you install it. Debian repackages it and changes the structure (just installed the current 2.0.3-3 version from the debian testing repo), this package still uses the commands.cfg and templates.cfg file in /etc/shinken. Probably due to historic reasons :/, but a vanilla 2.0.3 shinken doesn't anymore. I wonder what would be better in the documentation. Explanations for the vanilla version or the modified versions by the package maintainers. Now the etc structure looks like this:
```
ls -l
total 36
drwxr-xr-x 1 root root   22 Jan  8 17:55 arbiters
drwxr-xr-x 1 root root   20 Jan  8 17:55 brokers
-rw-r--r-- 1 root root 9936 Nov 11 16:31 commands.cfg
-rw-r--r-- 1 root root  513 Nov 11 16:31 contacts.cfg
drwxr-xr-x 1 root root  130 Jan  8 17:55 daemons
drwxr-xr-x 1 root root   26 Jan  8 17:55 hosts
drwxr-xr-x 1 root root  278 Jan  8 17:55 modules
drwxr-xr-x 1 root root   24 Jan  8 17:55 packs
drwxr-xr-x 1 root root   20 Jan  8 17:55 pollers
drwxr-xr-x 1 root root   30 Jan  8 17:55 reactionners
drwxr-xr-x 1 root root   20 Jan  8 17:55 realms
drwxr-xr-x 1 root root   24 Jan  8 17:55 receivers
-rw-r--r-- 1 root root  747 Nov 11 16:31 resource.cfg
drwxr-xr-x 1 root root   26 Jan  8 17:55 schedulers
-rw-r--r-- 1 root root 3585 Nov 11 16:31 shinken.cfg
-rw-r--r-- 1 root root 7513 Nov 11 16:31 templates.cfg
-rw-r--r-- 1 root root 2082 Nov 11 16:31 timeperiods.cfg
```
To me this looks basically like the 2.0.3 structure with a few modifications from the package maintainer.
Can you confirm this (basically looking like vanilla 2.0.3)?

**Comment by david-guenault** [comment] 2015-01-08 17:39
I can confirm that the layout changed a lot .... putting zach config file
in separate folder make it much more easier to find than every single file
in one folder. But nap is right configurations for nsclient should be put
in a pack available on shinken.io
Le 8 janv. 2015 18:21, "FrostbittenKing" <notifications@github.com> a écrit
:

**Comment by FrostbittenKing** [comment] 2015-01-08 17:45
K, thanks. I guess I will uninstall again the testing packages. They are unusable, in connection with the documentation. The maintainer thinks he is funny by changing a few things, and leaving out others idk. 
The debian packages contain (as mentioned in the docs) a commands.cfg and a templates.cfg, but the packaged version clearly is missing the windows host template that should be in the templates.cfg file. WTF, are the debian maintainers smoking? Crack?
Since I now understand more or less the differences between the packaged version and the vanilla version, I might as well install it via pip and use the split-up config files instead of the commands.cfg/templates.cfg file.

**Comment by naparuba** [comment] 2015-01-08 19:26
They mainly need testers to report, but not users that insults them then
they are doing a community work.

Please stop insults the project members. If you are not happy with
something, provide a patch. But your behavior is really bad for member
motivation and I won't allow this.


Jean

**Comment by FrostbittenKing** [comment] 2015-01-09 10:53
Yeah, I was a bit harsh, but I just can't wrap my head around this. How can you come up with such a package. Why change it in such a way, until it is not recognizable anymore? And no, I cannot provide a patch. I don't have the time and the motivation to dive into .deb packaging. There are others there for this. There is only so much I can do. I guess at least I should report it ;). It is so frustrating, trying to figure out how all the parts of shinken fall together, apply this to debian, and after 2 days of monkeying around with all the different installation methods for about 2-3h per day, I come to understand that the debian packages are just seriously -  let's be nice and call it - customized. I have to admit, I like the packaging policy of Arch Linux more. Don't know where it's codified but I would say it goes something like this: "We don't change the structure of a package". 
I was nearly giving up and trying another system, but the name "Shinken" alone appealed to me that I thought, I need to try this out, since it was the first beside Nagios I stumbled upon. 
Hint: Put a c into Shinken after the S (Schinken) means Ham in German :D. Yeah I know it is probably Japanese (at least it sounds very much Japanese), since it contains Syllables that can be put together from the Japanese (Shi-n-ke-n), but whatever (too much offtopic).

**Comment by dguenault** [comment] 2015-01-09 10:59
Well keep calm everybody, shinken is a framework that you can use to build
a complete monitoring solution. Not a packaged one like Nagios XI or
Zabbix. Some prefer packaged and others prefer to build their own. Deb
packaging is community driven and you should ask at the maintainer as we
are not the packagers. you can find packagers on irc.freenode.net on the
#shinken room (hvad for rpm and gstarck for deb).

2015-01-09 11:53 GMT+01:00 FrostbittenKing <notifications@github.com>:

**Comment by Seb-Solon** [comment] 2015-03-27 20:10
Looks like no PR was made to improve doc. I close this, PR a still welcome. 

If you have trouble with the packaging use the related board (debian / fedora or else) to report . It will be forwarded here if it's legit for upstream

**Closed by Seb-Solon** 2015-03-27 20:10 UTC
Labels: Documentation
