### ISSUE TITLE
Multiple level servicegroup

### ISSUE THREAD

**Issue by Azef1** [naparuba/shinken#1789] opened 2016-01-04 13:19 UTC
Hi,
I would like to do a multiple level servicegroup. (group child in group parent).

I created a servicegroup.cfg
>define servicegroup{
>   servicegroup_name      dev
   alias                  dev
   servicegroup_members   dev_child
}
define servicegroup{
   servicegroup_name   dev_child
   alias               dev_child
   members             localhost,http
}

and a service.cfg
>define service{
   service_description  http
   use                  generic-service
 #register             0
   host_name            localhost
   check_command        check_ntp
#servicegroups        dev_child
}

and i edit this file: 
`/usr/local/lib/python2.7/dist-packages/shinken/objects/servicegroup.py` and add
`'servicegroup_members': StringProp(fill_brok=['full_status']),`

The result is: 
![child](https://cloud.githubusercontent.com/assets/15362041/12090294/df90153e-b2ed-11e5-9458-5ed6440b6c30.PNG)

So the problem is "dev_child" is not include in "dev" group. And dev group is empty.

Thx

**Comment by olivierHa** [comment] 2016-01-04 14:06
Hello, 

Why closing ? Is this issue solved ? 

Regards

Olivier

**Comment by Azef1** [comment] 2016-01-04 14:15
Hi,
Because i think i posted in wrong forum and it's a problem about webui2 module
So i move to https://github.com/shinken-monitoring/mod-webui/issues/423 in module webui.

Thx

**Comment by geektophe** [comment] 2016-01-20 15:18
Currently, the child group members are only appended to the father group, the hierarchy is not  kept. The only way to reproduce it on the UI is to « manually » (because it is not represented by the way the objects are built) on the UI side by recursing the attribute.

It is not part of the standard attribute set, and could (should ?) be added, you're right (not only for servicegroups, but also for hostgroups and contactgroups).

**Comment by geektophe** [comment] 2016-01-21 11:59
Sorry, I had a look, it's already in the standard attribute set (at least in 2.4.2). I think this issue may be closed.

**Closed** 2016-01-21 12:51 UTC
