### ISSUE TITLE
service_excludes does not work on templates

### ISSUE THREAD

**Issue by N-Mi** [naparuba/shinken#1677] opened 2015-07-15 13:09 UTC
On Shinken 2.4.

When I try do remove a service from a template using the "service_excludes" directive, it has no effect. Using the same directive directly on a host works fine.

Here is a non-working configuration (TimeSync is a service defined in the "linux-snmp" pack") :

```
# Debian Squeeze
define host{
	name		squeeze
	register	0
	icon_set	server
	use		linux-snmp,ssh
	_SNMPCOMMUNITY	aaaaaaaaaaaaa
	_MAILTAG	[SYS]
	service_excludes	TimeSync
}

define host{
	use                     squeeze,dns,http,https
 	host_name               my-server1
	address			1.2.3.4
	alias			My Server 1

	_fs			/,/tmp,/usr,/var
}

```

This config works :

```
# Debian Squeeze
define host{
	name		squeeze
	register	0
	icon_set	server
	use		linux-snmp,ssh
	_SNMPCOMMUNITY	aaaaaaaaaaaaa
	_MAILTAG	[SYS]
}

define host{
	use                     squeeze,dns,http,https
	host_name               my-server1
	address			1.2.3.4
	alias			My Server 1

	_fs			/,/tmp,/usr,/var
	service_excludes	TimeSync
}

**Comment by eltismerino** [comment] 2015-07-31 16:35
I've got the same problem.

**Comment by geektophe** [comment] 2015-08-25 15:26
The problem is due to a regression introduced in a previous commit. It's fixed in https://github.com/naparuba/shinken/pull/1703.

**Comment by N-Mi** [comment] 2015-08-25 16:51
Very nice !
I'm testing the fix as soon as possible to confirm if the issue is solved.

**Closed** 2016-04-30 12:49 UTC
