### ISSUE TITLE
[Shinken 2.4] problem with service_description in service template 

### ISSUE THREAD

**Issue by rom1701** [naparuba/shinken#1638] opened 2015-05-20 11:24 UTC
I have a problem after upgrading of shinken 2.0.3 to shinken 2.4

the commande shinken-arbiter -v -c /etc/shinken/shinken.cfg return errors like:
ERROR: [Shinken] [service::UNKNOWN-SERVICE] a service item has been defined without unique_key in /etc/shinken/...

I think with the new version, i can't write a service description in a service template:
in my host configuration
define host{
        use             linux
        host_name       test
        address         localhost
}
define service{
        use             template-test-service
        host_name       test
}

in my template configuration
define service{
        use             local-service
        name            template-test-service
        service_description test
        check_command    check_ping!100.0,20%!500.0,60
        contact_groups  admin
}

my configuration works with nagios or shinken 2.0.3, so I don't understand

**Comment by k0ste** [comment] 2015-05-21 03:04
service_description inherit broken in 2.2 (https://github.com/naparuba/shinken/issues/1472), and don't fixed in 2.4 (https://github.com/naparuba/shinken/issues/1635)

**Comment by rom1701** [comment] 2015-05-21 11:01
thank,
do you think it can be fixed in future? because with this error, the arbiter don't want of my configuration. I have a big failed.

**Comment by k0ste** [comment] 2015-05-22 04:24
I wait this fix few months...

**Comment by Letherofile** [comment] 2015-06-12 11:42
I have the same problem and I use a lot capabilities template. It's a big problem for me.
Someone know in wich file this bug can occured ?
Or maybe it's a deprecated feature to use serice_description in template service ?
Thank

**Comment by rom1701** [comment] 2015-06-12 12:05
I don't know, but you can stay if you want in the 2.0.3 version and wait, but you can have some problems like bad load balancing of the scheduler, etc...

**Comment by olivierHa** [comment] 2015-06-12 20:18
I will try to look at this bug next week and see what is going wrong with that.
Regards

Olivier

**Comment by k0ste** [comment] 2015-06-19 16:47
Any news?

**Comment by Routhinator** [comment] 2015-06-27 19:36
Confirming this issue in 2.4

Workaround is to remove the description from the service.. which isn't very useful.

**Comment by rom1701** [comment] 2015-07-02 14:55
I confirm, if I comment service_description in a service template, the arbiter accept the new configuration. But i think it can generated a new problem with graphite, because carbon-cache use service_description for name the directory where the whisper base is saved. I need to test for confirm this idea.

**Comment by Letherofile** [comment] 2015-07-03 10:03
"remove the description from the service" ?
service_description is a required directive in service definition.
If i remove it, the arbiter can't restart : 
ERROR: [Shinken] [service::...] a service has been defined without service_description in unknown
ERROR : [Shinken] services conf incorrect!!

**Comment by olivierHa** [comment] 2015-07-07 19:46
Sorry for the delay, i will look into it.

**Comment by olivierHa** [comment] 2015-07-07 21:13
Ok I can't reproduce this issue.

But looking at the configuration, the error 'a service item has been defined without unique_key', is coming from a missing "register 0" in your definition.

I've pushed 2 new tests (which are "green") : 

https://github.com/naparuba/shinken/commit/53c70ee51a7f05904bcd78f680f0655bd5478278

What did I miss in those tests ?

Could you give me a "not" working configuration ?

Regards

Olivier

**Comment by k0ste** [comment] 2015-07-08 03:31
**olivierHa**, https://github.com/naparuba/shinken/issues/1635#issue-77914218

**Comment by olivierHa** [comment] 2015-07-08 08:35
Ok, i can reproduce it with a real "run", not a testcase ... Strange

**Comment by rom1701** [comment] 2015-07-08 11:42
if this can help you, i have a configuration more complex and generate error in check config:
define host{
    use                            linux
    host_name                localhost
    address                     localhost
}

define hostgroup{
hostgroup_name           test
alias                              hostgroup for test
members                       localhost
}

define servicegroup{
servicegroup_name       servicegroup_name
alias                               servicegrouptest
}

define service{
use                                 template-test-service
hostgroup_name            test
servicegroups                 servicegroup_name
contact_groups               admins
}

define service{
use                                  local-service
name                               template-test-service
service_description         test
check_command             check_ping!100.0,20%!500.0,60
contact_groups               admin
register                           0
}

**Comment by olivierHa** [comment] 2015-07-08 20:44
Could you give a try with master version ?

**Closed** 2015-07-08 20:43 UTC

**Comment by k0ste** [comment] 2015-07-09 04:03
**olivierHa**, I patch 2.4 with https://github.com/naparuba/shinken/commit/4715b8dbba4335e2f6c0cbecea3914a83109d932, works good.

**Comment by rom1701** [comment] 2015-07-09 08:07
Sorry but for me , with my example, I have always the same problem , i dont understand .

[1436429148] ERROR: [Shinken] [service::localhost/test] a service item has been defined without unique_key in /etc/shinken/hosts/localhost.cfg:18
[1436429148] ERROR: [Shinken] [items] In test is incorrect ; from /etc/shinken/hosts/localhost.cfg:18
[1436429148] ERROR: [Shinken]   services conf incorrect!!
 but with 2.0.3 it's OK

**Comment by k0ste** [comment] 2015-07-09 08:34
**rom1701**, you are not defined host_name of service on line 18.

**Comment by rom1701** [comment] 2015-07-09 08:48
If i use hostgroup_name, I didn't  need host_name. And if you are right, the problem is I don't have host_name, why it's run on nagios, and shinken 2.0.3?

**Comment by rom1701** [comment] 2015-07-09 10:46
For information, this error always appears with the new patch

**Comment by olivierHa** [comment] 2015-07-09 18:54
The error 'a service item has been defined without unique_key' is about a missing "register 0".

**Comment by geektophe** [comment] 2015-08-28 20:47
The problem should be fixed in https://github.com/naparuba/shinken/pull/1710. Could you have a test and confirm it worked for you ?
