### ISSUE TITLE
 Services disappearing from thruk on config change and arbiter restart 

### ISSUE THREAD

**Issue by mobarre** [naparuba/shinken#1691] opened 2015-08-06 15:13 UTC
We're having a strange issue on our current production Shinken servers. When restarting the arbiter to take into account a configuration modification, some services might not show up on Thruk. If I restart the arbiter a second time, all is well.

I managed to double check that:
In the arbiterd.log, I always get the right number of services ("[1435131526] INFO: [Shinken] Checked 1238 services")
If I dump the shinken configuration as a json file to parse it myself, I do get the right service count each time.

It seems only Thruk/Livestatus has issues

Version information:
Shinken 2.4
Thruk 1.88-4
Latest livestatus module

What information can I provide to help ?
Note: I'm not afraid of getting my hands in the code a bit.

**Comment by floppy84** [comment] 2015-08-17 08:22
I got the same issue since my upgrade to 2.4 and thruk 1.88-4 in June.
Naparuba informed me that it come from Livestatus module and it will take some time for fix it.
I don't have any additionnal information since a month.

i have to make a second restart like you and check if i got the same number of service check before and after restart.

**Comment by mobarre** [comment] 2015-08-17 12:38
I'm going to need to add some info on this. The issue is actually larger than I thought.
- I've been able to link a new symptom to this: when a service is modified and the arbiter restarted, you might see the service "doubled" in thruk (a telnet request to the livestatus modules confirms that the issue is on the data that is returned by the livestatus)

- The workaround we're using now is to restart the broker once the arbiter has restarted. It'll start fresh and pull a conf from the arbiter. No more services missing and no more services doubled.

Note that the doubled services are not that easy to replicate. It doesn't always happen.

**Comment by olivierHa** [comment] 2015-08-17 12:45
Since 2.4 i am doing the same thing :  reload arbiter+broker when doing a
configuration change.
Not ideal, but it is a workaround.



2015-08-17 14:38 GMT+02:00 Marc-Olivier Barre <notifications@github.com>:

**Comment by floppy84** [comment] 2015-08-17 14:03
Thanks for the this little trick about services doubled.

i observe in broker log this error.
Perhaps unrelated things with issue:

1439819312] ERROR: [broker-master] [Livestatus Query] Error: 'Services' object has no attribute '__itersorted__'
[1439819312] ERROR: [broker-master] [Livestatus Query] Error: 'Services' object has no attribute '__itersorted__'
[1439819312] ERROR: [broker-master] [Livestatus Query] Error: 'Services' object has no attribute '__itersorted__'
[1439819319] ERROR: [broker-master] [Livestatus Query] Error: 'Services' object has no attribute '__itersorted__'
[1439819319] ERROR: [broker-master] [Livestatus Query] Error: 'Hosts' object has no attribute '__itersorted__'
[1439819321] ERROR: [broker-master] [Livestatus Query] Error: 'Services' object has no attribute '__itersorted__'

**Comment by floppy84** [comment] 2015-08-26 08:02
no update ?

**Comment by mobarre** [comment] 2015-08-26 08:19
I'm wondering if the project is dead or if people are just taking a vacation...

**Comment by olivierHa** [comment] 2015-08-26 08:25
Nap is on vacation. Same things for other contributors.
No time on my side to investigate more on this issue,
And a workaround is provided ... (or you can stay in Shinken 2.0.3)

Olivier

2015-08-26 10:19 GMT+02:00 Marc-Olivier Barre <notifications@github.com>:

**Comment by mobarre** [comment] 2015-08-26 09:09
No worries mate. We're all a little bit on the edge on our project right now. The workaround is fine and we're even working on getting commercial support anyways ;)

**Comment by floppy84** [comment] 2015-09-22 08:10
no update ?

**Comment by floppy84** [comment] 2015-10-22 08:34
I would like to fix this issue, could you give me an update on this ?

**Comment by geektophe** [comment] 2015-10-27 07:32
Just to be sure, are you using the last livestatus version ? The last tag is 1.4.2 on https://github.com/shinken-monitoring/mod-livestatus/releases.

**Comment by floppy84** [comment] 2015-10-27 11:15
Yes i got the last shinken livestatus module.

**Comment by activars** [comment] 2015-11-29 12:42
We experience the same issue. To resolve it, we had to restart shinken-broker after restarting shinken-arbitor. Although this is not ideal because the broker restart will take a 30-60 seconds to recover.

**Comment by ianling** [comment] 2015-12-09 21:13
I am getting this issue even without a config change/arbiter restart. Livestatus will just sometimes just lose services and hosts for no reason. The arbiter log always shows that it detects the correct amount of hosts and services (1200 hosts and 2000 services), but in Livestatus, it will occasionally lose some and report that there are only 900 hosts and 1200 services. It usually clears itself up after a while, but it is annoying to have to restart the arbiter and broker repeatedly before they will display the correct number of hosts and services.

**Comment by activars** [comment] 2015-12-09 22:10
it would be great to get a patch release soon... thank you!

**Comment by ianling** [comment] 2015-12-10 00:03
This is now happening constantly, and I cannot get it to work correctly again. As soon as I restart the arbiter and broker, it reports the correct number of hosts and services for about 5 seconds, and then it fluctuates a lot, before finally mostly settling at an incorrect number of hosts/services. It makes Shinken unusable for us, as we make extensive use of Check_MK.

**Comment by olivierHa** [comment] 2015-12-10 09:21
Hello everyone,

Have you enabled the webui module ? Are hosts/services also missing in the
webui dashboard ?
Are checks on missing hosts still happening ? (so scheduler/poller are
still doing their job)

In fact, I am curious to see if this is an issue with the livestatus
module, or something in the shinken core.

Thanks for your feedback.

2015-12-10 1:03 GMT+01:00 Ian <notifications@github.com>:

**Comment by floppy84** [comment] 2015-12-10 10:12
Hi, for me webui module is enable. However i can't say if service disappearing from shinken webui too because i don't have like thruk a total service counter. And each time i reload shinken i don't really know which service diseappear, i just see that the counter of service is under the previous counter of service after reboot.

regards

**Comment by mohierf** [comment] 2015-12-10 10:36
Which version of webui did you installed? With the last one you can have the total number of hosts/services in the header bar ...

**Comment by floppy84** [comment] 2015-12-10 15:33
I am on Webui version 1, i can't change for the moment

**Comment by ianling** [comment] 2015-12-10 16:10
@olivierHa - Service and host checks still run on the hosts/services that have disappeared from Livestatus; I still get notifications about those hosts if they go down, and the perfdata for the services still gets written to the pnp4nagios perfdata folder.

**Comment by activars** [comment] 2015-12-10 16:25
confirm this is the same behaviour we experience.

**Comment by ianling** [comment] 2015-12-10 17:41
@olivierHa - I enabled WebUI and found that when I try to look at one of the services that has disappeared, I get the following error and stack trace...

    AttributeError("'NoneType' object has no attribute 'get_webui_port'",)

    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4.2-py2.7.egg/shinken/webui/bottlewebui.py", line 686, in _handle
        return callback(**args)
      File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4.2-py2.7.egg/shinken/webui/bottlewebui.py", line 1357, in wrapper
        rv = callback(*a, **ka)
      File "/var/lib/shinken/modules/webui/module.py", line 517, in lock_version
        return f(**args)
      File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4.2-py2.7.egg/shinken/webui/bottlewebui.py", line 2749, in wrapper
        return template(tpl_name, **tplvars)
      File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4.2-py2.7.egg/shinken/webui/bottlewebui.py", line 2723, in template
        return TEMPLATES[tpl].render(kwargs)
      File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4.2-py2.7.egg/shinken/webui/bottlewebui.py", line 2695, in render
        self.execute(stdout, kwargs)
      File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4.2-py2.7.egg/shinken/webui/bottlewebui.py", line 2687, in execute
        return subtpl.execute(_stdout, rargs)
      File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4.2-py2.7.egg/shinken/webui/bottlewebui.py", line 2681, in execute
        eval(self.co, env)
      File "/var/lib/shinken/modules/webui/views/layout.tpl", line 117, in <module>
        %include header_element globals()
      File "/usr/local/lib/python2.7/dist-packages/Shinken-2.4.2-py2.7.egg/shinken/webui/bottlewebui.py", line 2669, in subtemplate
        return self.cache[_name].execute(_stdout, kwargs)
    AttributeError: 'NoneType' object has no attribute 'get_webui_port'

**Comment by ianling** [comment] 2015-12-11 16:38
The error I get in Check_MK occasionally is this:

    Shinken - Livestatus error
    Unhandled exception: 500: Internal server error: KeyError(2137,)

No stack trace unfortunately.

**Comment by ianling** [comment] 2015-12-11 22:20
Here's a debug brokerd log: http://pastebin.com/Nyx7fDk4

The <...> are parts where I've removed lines that just repeat a lot.

**Comment by ianling** [comment] 2015-12-14 18:11
Another interesting detail: I have a python script I made that queries Livestatus for all hostnames. This always returns the full list of host names! Not sure why Check_MK and webui are not working correctly... Here is the code from my script:

    from mk_livestatus import Socket

    UI_index = Blueprint('UI_index', __name__)
    sock = Socket("/usr/local/shinken/var/rw/live")
    hostsQuery = sock.hosts.columns('host_name')
    hostsList = hostsQuery.call()

This script uses the named pipe to communicate with livestatus though, not TCP. I wonder if that has anything to do wit hit.

**Comment by olivierHa** [comment] 2015-12-14 20:30
Hum, you said that webui aren't working correctly ? I thought
hosts/services were missing only on backend using Livestatus, but not on
webui.

I will try to install webui this weekend, and reproduce your test case, ie
hosts missing in check_mk, but are still returned by a livestatus request.

Regards

Olivier

2015-12-14 19:11 GMT+01:00 Ian <notifications@github.com>:

**Comment by ianling** [comment] 2015-12-14 20:32
Disregard my last message Olivier, I ended up finding that my script actually only works intermittently; sometimes it returns the correct, expected result, sometimes it doesn't. 

So the problem exists in both livestatus and webui.

**Comment by floppy84** [comment] 2015-12-22 09:18
Any update about this ? the fix will be in the next release ? when the next release is planed to be publish ?

**Comment by olivierHa** [comment] 2015-12-23 09:28
We still need to find what the root cause of this issue.
A next release of Shinken will be published in January, I hope we will
correct this issue before, so the fix will be included in it.


2015-12-22 10:18 GMT+01:00 floppy84 <notifications@github.com>:

**Comment by ianling** [comment] 2015-12-23 17:32
Another error from the broker log that may be relevant....

    [1450891639] ERROR: [broker-master] [Livestatus] Unexpected error during process of request 'GET hosts\nColumns: host_scheduled_downtime_depth host_last_state_change host_pnpgraph_present host_icon_image host_plugin_output host_is_flapping host_in_notification_period host_action_url_expanded host_modified_attributes_list host_downtimes host_filename host_acknowledged host_custom_variable_names host_state host_comments_with_extra_info host_accept_passive_checks host_has_been_checked host_address host_staleness host_notifications_enabled host_active_checks_enabled host_perf_data host_custom_variable_values host_name host_check_command host_notes_url_expanded\nFilter: host_acknowledged = 0\nFilter: host_state = 0\nFilter: host_has_been_checked = 1\nAnd: 2\nNegate:\nFilter: host_has_been_checked = 1\nFilter: host_scheduled_downtime_depth = 0\nFilter: host_custom_variable_names < _REALNAME\nLocaltime: 1450891639\nOutputFormat: python\nKeepAlive: on\nResponseHeader: fixed16\nLimit: 1001\n\n' : 619
    [1450891639] ERROR: [broker-master] [Livestatus] Back trace of this exception: Traceback (most recent call last):
      File "/var/lib/shinken/modules/livestatus/livestatus_obj.py", line 75, in handle_request
        return self.handle_request_and_fail(data)
      File "/var/lib/shinken/modules/livestatus/livestatus_obj.py", line 132, in handle_request_and_fail
        output, keepalive = query.process_query()
      File "/var/lib/shinken/modules/livestatus/livestatus_query.py", line 283, in process_query
        return self.response.respond()
      File "/var/lib/shinken/modules/livestatus/livestatus_response.py", line 147, in respond
        responselength = 1 + self.get_response_len() # 1 for the final '\n'
      File "/var/lib/shinken/modules/livestatus/livestatus_response.py", line 142, in get_response_len
        if isinstance(rsp, LiveStatusListResponse)
      File "/var/lib/shinken/modules/livestatus/livestatus_response.py", line 83, in total_len
        for generated_data in value:
      File "/var/lib/shinken/modules/livestatus/livestatus_response.py", line 278, in make_live_data_generator
        for value in self.make_live_data_generator2(result, columns, aliases):
      File "/var/lib/shinken/modules/livestatus/livestatus_response.py", line 224, in make_live_data_generator2
        item = next(result)
      File "/var/lib/shinken/modules/livestatus/livestatus_query.py", line 53, in gen_limit
        for val in values:
      File "/var/lib/shinken/modules/livestatus/livestatus_query.py", line 46, in gen_filtered
        for val in values:
      File "/var/lib/shinken/modules/livestatus/livestatus_regenerator.py", line 125, in itersorted
        yield self.items[id]
    KeyError: 619

**Comment by ianling** [comment] 2015-12-29 00:23
If anyone is still experiencing this issue, check to make sure that you do not have multiple instances of the arbiter running. I just ran into an issue where there were several distinct arbiter instances running, each trying to send out different configurations, which was causing a number of issues. Killing all instances of the arbiter and then starting it again fixed this issue for me.

Do `service shinken-arbiter stop` first. At this point, the arbiter should not be running at all. Next, run `ps aux | grep shinken` to see how many instances are still running. If there are any, kill them, and then `service shinken-arbiter start` and see if the problem has disappeared.

It looks like the arbiter just sometimes fails to be killed when you restart it, so previous instances may accumulate and cause problems.

**Comment by olivierHa** [comment] 2016-01-12 22:24
Regarding this issue,  can someone try this PR #1783 and give me some feedback ?

**Comment by olivierHa** [comment] 2016-02-27 09:57
Any feedbacks ?

**Comment by floppy84** [comment] 2016-02-29 03:45
is there any danger to do modifications ? do i need to edit each file on my shinken env like your PR ?

**Comment by mobarre** [comment] 2016-02-29 09:16
FYI: I'll be testing the PR today

**Comment by mobarre** [comment] 2016-02-29 11:19
Applied the path (had to it it manually, generated a patch from git diff, applied on prod and skipped the test suite files that weren't there, rock'n roll). So far so good.

I did a quick test which used to mess with my services: comment out 1 service in the shinken config, restart arbiter only. It used to remove half my services. Now I only saw the 1 service I removed disappear from thruk. Much better :)

Any one else managed to test this ?

**Comment by floppy84** [comment] 2016-02-29 15:29
I have applied the fix on file concerned.
But i still have the issue.
Some services disappearing from thruk on config change.
Before reload 6752 services and after 6624.

**Comment by mobarre** [comment] 2016-03-01 08:13
ok, I tested again this morning and it still works fine. maybe I'm doing it wrong. I tested this by commenting out one of my hosts and restarting shinken arbiter. I only lost 1 host and 9 services as expected. then I uncommented it and restarted again. I ended up with the right amount of services again.
@floppy84: are you doing something different as a test ?

**Comment by kastesh** [comment] 2016-03-01 09:23
Hello, 
I've applied this patch one week ago. It removes some of the problems because I see a smaller number of restarts during the day in the log files.

However restarter-script still have found differences in arbiter data and livestatus data. 
Some of them related to livestatus problems which mentioned at the top:
`[1456799041] ERROR: [broker-master] Unexpected error: 'e2f32530df5311e5ab5e00505601083e' ; traceback: Traceback (most recent call last):
  File "/var/lib/shinken/modules/livestatus/livestatus_client_thread.py", line 254, in run
    self.handle_request(request_bytes)
  File "/var/lib/shinken/modules/livestatus/livestatus_client_thread.py", line 237, in handle_request
    self.send_response(response)
  File "/var/lib/shinken/modules/livestatus/livestatus_client_thread.py", line 208, in send_response
    for data in response:
  File "/var/lib/shinken/modules/livestatus/livestatus_response.py", line 66, in __iter__
    for v2 in value:
  File "/var/lib/shinken/modules/livestatus/livestatus_response.py", line 278, in make_live_data_generator
    for value in self.make_live_data_generator2(result, columns, aliases):
  File "/var/lib/shinken/modules/livestatus/livestatus_response.py", line 224, in make_live_data_generator2
    item = next(result)
  File "/var/lib/shinken/modules/livestatus/livestatus_query.py", line 46, in gen_filtered
    for val in values:
  File "/var/lib/shinken/modules/livestatus/livestatus_regenerator.py", line 125, in itersorted
    yield self.items[id]
KeyError: 'e2f32530df5311e5ab5e00505601083e'`
After this errors broker-service is restarted and LV data filled in again - this is one reason when restarter- script detects differences.

For others I don't find any related errors in broker log file. For example:
`[2016-03-01 12:05:02]  36942 [info] "Close /var/lib/shinken/rw/live"
[2016-03-01 12:05:02]  36942 [info] "There are 1181 hosts in the livestatus"
[2016-03-01 12:05:02]  36942 [info] "There are 1182 hosts in the arbiter log file"
[2016-03-01 12:05:02]  36942 [info] "Connected to /var/lib/shinken/rw/live"
[2016-03-01 12:05:02]  36942 [info] "Send request to /var/lib/shinken/rw/live size=53"
[2016-03-01 12:05:04]  36942 [info] "Close /var/lib/shinken/rw/live"
[2016-03-01 12:05:04]  36942 [info] "There are 8283 services in the livestatus"
[2016-03-01 12:05:04]  36942 [info] "There are 8313 services in the arbiter log file"
`
Perhaps it has something to do with the number of changes in our monitoring system. 
We use Shinken 2.4.2 (3 realms, one arbiter and one broker). We are monitoring the autoscaling-groups; during the day about 50-150 hosts can be added and removed from the monitoring system. The peak of restarts occurs in moments when autoscaling-groups change.

**Comment by floppy84** [comment] 2016-03-01 10:40
@mobarre i am done the same test than you.
And i always have issue on livestatus in log file :+1: 

[1456825773] ERROR: [broker-master] [Livestatus] Unexpected error during process of request 'GET services\nColumns: accept_passive_checks acknowledged.

Moreover it seems to impact only the services from Sydney realms, perhaps an issue due to  the latency to connect to sydney from europe ?

**Comment by mobarre** [comment] 2016-03-01 11:02
@floppy84: I just double checked. New attempt with both hosts and services disabled across multiple realms. No effect and no Livestatus ERROR message like you have (I just get a "Error: 'Services' object has no attribute '__itersorted__'" which has been here for a while and doesn't seem to harm our service)

Are you sure the patch has been applied properly ? I could make you a patch ready for a 2.4.2 live install (the one you make from the github PR is to be applied on the source dir and the PR seems to be based on the current master, so there's a few things to modified to get it right).

**Comment by floppy84** [comment] 2016-03-01 11:37
Ok perhaps i made a mistake. i just replace the 7 files changed in the PR.

![image](https://cloud.githubusercontent.com/assets/3499449/13425692/c2e21008-dfa8-11e5-9ad7-9efdb4c2e1f3.png)

i made this change in directory :
/usr/local/src/shinken-master/shinken/

perhaps is this directory instead  of previous one :  /usr/lib/python2.6/site-packages/Shinken-2.4-py2.6.egg/shinken/

thanks for your help

**Comment by floppy84** [comment] 2016-03-01 14:33
So, i confirm i made a mistake in directory to update.

Do i need to update from 2.4 to 2.4.2 before apply the PR ?

Because i tryed to modify the file like the PR, but this time from the good directory.
And on reload i got : 

Traceback (most recent call last):
  File "/usr/bin/shinken-arbiter", line 73, in <module>
    from shinken.daemons.arbiterdaemon import Arbiter
  File "/usr/lib/python2.6/site-packages/Shinken-2.4-py2.6.egg/shinken/daemons/arbiterdaemon.py", line 36, in <module>
    from shinken.objects.config import Config
  File "/usr/lib/python2.6/site-packages/Shinken-2.4-py2.6.egg/shinken/objects/__init__.py", line 43, in <module>
    from host import Host, Hosts
  File "/usr/lib/python2.6/site-packages/Shinken-2.4-py2.6.egg/shinken/objects/host.py", line 38, in <module>
    from shinken.util import (format_t_into_dhms_format, to_hostnames_list, get_obj_name,
ImportError: cannot import name get_exclude_match_expr


I think it come from my version of shinken. could you confirm that ?

Regards

**Comment by olivierHa** [comment] 2016-03-01 14:40
Hello,

Yes, you should upgrade first to 2.4.2 before trying to apply this PR.

Regards

Olivier

2016-03-01 15:33 GMT+01:00 floppy84 <notifications@github.com>:

**Comment by mobarre** [comment] 2016-03-01 14:40
@olivierHa you where faster than me to write this... :)

**Comment by olivierHa** [comment] 2016-03-02 08:25
About the "KeyError" stacktrace, this is "normal" during startup or change configuration phase.
During those phases, the hash containing all the hosts/services are 'switched', but this is not an atomic operation, so sometimes a KeyError appears.

But this shouldn't happen during the "run" time.

Maybe we should catch and hide those keyerror and not raise the exception. A lot of people are worried to see that. @naparuba  ?

**Comment by kastesh** [comment] 2016-03-02 13:05
I checked shinken files and found all the changes from the PR.
My location for Shinken files is  /usr/lib/python2.6/site-packages/Shinken-2.4.2-py2.6.egg on the server.
I've uploaded final result to [https://github.com/kastesh/shinken-2.4.2-replace](url). Sorry, I didn't save original files and couldn't give diff.

I am very sorry to say it, but I still find differences between LV and arbiter's info.
For example
Autoscaling daemon removed host's configuration (it initiates process):
```
[2016-03-02 05:59:46]  32959 [info] "Delete Instance=i-XXXXXX from monitoring"
[2016-03-02 05:59:46]  32959 [info] "Delete configuration file: /etc/shinken/hosts/us/i-XXXXXX.cfg"
[2016-03-02 05:59:47]  32959 [info] "Service restart: /sbin/service shinken reload"
```

Arbiter read new configuration at Wed Mar  2 06:00:39 MSK 2016:
`[1456887639] INFO: [Shinken] 	Checked 1123 hosts`

The checker/restarter script saved to the log (before the arbiter service was reloaded) :
```
[2016-03-02 06:00:02]  11991 [info] "There are 1124 hosts in the livestatus"
[2016-03-02 06:00:02]  11991 [info] "There are 1124 hosts in the arbiter log file"
[2016-03-02 06:00:05]  11991 [info] "There are 6411 services in the livestatus"
[2016-03-02 06:00:05]  11991 [info] "There are 6411 services in the arbiter log file"
```
The checker/register script saved to log (after the arbiter service was reloaded):
```
[2016-03-02 06:01:01]  19202 [info] "There are 1124 hosts in the livestatus"
[2016-03-02 06:01:01]  19202 [info] "There are 1123 hosts in the arbiter log file"
[2016-03-02 06:01:03]  19202 [info] "There are 6411 services in the livestatus"
[2016-03-02 06:01:03]  19202 [info] "There are 6381 services in the arbiter log file"
```
May be, it is different situation, because, I don't have missing services in LV, but there are trapped services  and hosts.

**Comment by mobarre** [comment] 2016-03-02 15:06
To help  out those who are willing to test, here's a patch you can use on an existing 2.4.2 install :
[--> Restart patch](http://pastebin.com/8gAqM2pq)

cd to /usr/lib/python2.7/site-packages/shinken and run
`patch -p1 < <path to patch>`

**Comment by kastesh** [comment] 2016-03-02 16:02
@mobarre , thank you for patch.
I have reverted shinken installation to the origin files by:
`pip install --upgrade --force-reinstall shinken`
and use the patch.

Tomorrow I will tell, if there is trapped host and services.

**Comment by floppy84** [comment] 2016-03-09 09:09
Hi all,

I made the upgrade yesterday to 2.4.2 and applyed the patch.

All seems to work now, and no issue with reload.

Congrat and than you !!!

**Comment by olivierHa** [comment] 2016-03-09 16:12
Pr is merged into master.
A 2.4.3 version will be released.

**Closed by olivierHa** 2016-03-09 16:12 UTC
