### ISSUE TITLE
Initial state must be OK

### ISSUE THREAD

**Issue by hvad** [naparuba/shinken#1694] opened 2015-08-11 15:29 UTC
Hi,

Initial state is PENDING but it should be OK.

Saw in -> https://shinken.readthedocs.org/en/latest/08_configobjects/service.html#configobjects-service
"By default Shinken will assume that all services are in OK states when in starts. " 

Best regard

**Comment by olivierHa** [comment] 2015-08-15 14:42
I think Pending is the correct value, we just need to fix the doc not the code.

**Comment by hvad** [comment] 2015-08-15 14:49
I don't think so. First, initia_state doesn't work. Second you can't use correctly passive service with initial_state Pending.

**Comment by olivierHa** [comment] 2015-08-15 15:10
I will try to reproduce it. For me Pending=ok in term of value (o), so it
should work for passive checks.

**Comment by hvad** [comment] 2015-08-15 18:24
initial_state isn't present in shinken code version 2.4.1 and you can set initial_state that why it can't work. And Pending state it's not Ok.

**Comment by mobarre** [comment] 2015-08-19 18:39
My 2 cents as a shinken user (in production... it's actually the thing that wakes me up with an SMS when our 2 million user platform goes down in flames):
When a manager looks at our dashboard displayed on a way too big TV screen in the openspace and sees something that isn't green (OK) but that is grey (PENDING), He will ask why it is not OK. While I do know it's a silly question, my manager doesn't.
We do use passive checks (yup, SNMP traps are a thing when it comes to network equipment or SAN disk state) and until a trap is received, it's not green.
Then again, maybe a passive check overhaul would help, because shinken (and nagios for that matter) for passive checks really isn't ideal. And I don't want to end up using a specialized tool for passive checks: I like my shinken ;)

**Comment by hvad** [comment] 2015-08-19 19:08
Hi,

There's two things for that issue : 

- first : documentation say "By default Shinken will assume that all services are in OK states when in starts." but it false initial state is PENDING. 

- second : initial_state doesn't work, you can initialise a passive service with initial_state = o.

I test a patch but i think we must discuss with Jean to that issue.

Best regard

**Comment by geektophe** [comment] 2015-08-29 08:58
I also think that the ability to set an `initial_state`, which defaults to `PENDING`, but is configurable for specific instances, would be a valuable addition. I have passive host and service checks in mind also.

I'll have a look at this.

**Comment by geektophe** [comment] 2015-08-29 21:33
I created a PR to take into account the `initial_state` attribute, which is ignored by now: https://github.com/naparuba/shinken/pull/1711. It should do what you want.

**Comment by olivierHa** [comment] 2015-10-01 07:27
I am closing. PR has been merged.
I will be in the next release

**Closed by olivierHa** 2015-10-01 07:27 UTC
Labels: Bug
